### ISSUE TITLE
Certificados duplicados

### ISSUE THREAD

**Issue by kaioduarte** [hydrocat/certificados_utfpr#1]
O antepenúltimo e o penúltimo são iguais.

![image](https://user-images.githubusercontent.com/11046907/45003142-9c3d3b00-afb5-11e8-9631-6ae30eeed5a1.png)

**Comment by hydrocat** [comment]
Isso acontece porque alguns eventos estão duplicados também.
Por exemplo, em *Campo Mourão*, no ano *2016* existe duas entradas para o evento *Introdução a física quântica*.

**Comment by kaioduarte** [comment]
Entendi, mas se usar um `set` já resolve :wink:
